name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Change this if your default branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # or any version you need

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Copy sprints.html to sprints/index.html
        run: |
          mkdir -p dist/sprints
          cp dist/sprints.html dist/sprints/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

  add-subtrees:
    runs-on: ubuntu-latest
    needs: build-and-deploy  # Ensures build runs first

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          persist-credentials: true

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add subtree 15
        run: |
          git subtree add --prefix sprints/15 https://github.com/opengeospatial/dev-ogc-org-sprint-landing-15.git gh-pages --squash || echo "Subtree may already exist"

      - name: Add subtree 16
        run: |
          git subtree add --prefix sprints/16 https://github.com/opengeospatial/dev-ogc-org-sprint-landing-16.git gh-pages --squash || echo "Subtree may already exist"

      - name: Add subtree 17
        run: |
          git subtree add --prefix sprints/17 https://github.com/opengeospatial/dev-ogc-org-sprint-landing-17.git gh-pages --squash || echo "Subtree may already exist"

      - name: Add subtree sponsoring
        run: |
          git subtree add --prefix sprints/sponsoring https://github.com/opengeospatial/dev-sprint-sponsoring.git gh-pages --squash || echo "Subtree may already exist"

      - name: Add subtree nodes
        run: |
          git subtree add --prefix sprints/nodes https://github.com/ogcincubator/code-sprint-nodes.git gh-pages --squash || echo "Subtree may already exist"